spring:
    #    main:
    #        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        -   id: user-module
                            uri: lb://USER-MODULE
                            predicates:
                                - Path=/api/v1.0/moviebooking/register, /api/v1.0/moviebooking/login, /api/v1.0/moviebooking/*/forgot, /api/v1.0/moviebooking/all
                            filters:
                                - StripPrefix=3
                        -   id: movie-and-theatre-module
                            uri: lb://MOVIE-AND-THEATRE-MODULE
                            predicates:
                                - Path=/api/v1.0/moviebooking/movies/**
                            filters:
                                - StripPrefix=4
                        -   id: tickets-module
                            uri: lb://TICKETS-MODULE
                            predicates:
                                - Path=/api/v1.0/moviebooking/*/add, /api/v1.0/moviebooking/tickets/**
                            filters:
                                - StripPrefix=3
#            globalcors:
#                cors-security:
#                    '[/**]':
server:
    port: 8090

management:
    endpoints:
        web:
            exposure:
                include: "*"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka