spring:
    application:
        name: user-module
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
        driverClassName: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update # Automatically updates the database schema based on entities
        show-sql: true # Logs SQL queries to the console
    session:
        jdbc:
            initialize-schema: always
    messages: # Use My Properties file: error.property
        basename: error
        encoding: UTF-8
        fallback-to-system-locale: false

logging:
    level:
        # Log the SQL statements
#        root: DEBUG
        org:
            hibernate:
#                SQL: DEBUG
        # Log the binding parameters (TRACE level provides more detail than DEBUG)
#        org.hibernate.orm.jdbc.bind: TRACE
server:
    port: 8081

springdoc:
    openapi:
        info:
            title: User REST API Documentation
            description: This is the REST API Documentation for Handling the User Module
            version: v1.0
    apiDocs:
        enabled: true
    swaggerUi:
        enabled: true

eureka:
   client:
       service_url:
            defaultZone: https://bookamovie-spring-boot-eureka-server-fe3s.onrender.com/eureka