spring:
  application:
    name: tickets-module
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update # Automatically updates the database schema based on entities
  show-sql: true # Logs SQL queries to the console
  session:
    jdbc:
      initialize-schema: always
  messages: # Use My Properties file: error.property
    basename: error
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: 8083


springdoc:
  openapi:
    info:
      title: Tickets REST API Documentation
      description: This is the REST API Documentation for the Tickets (Ticketing) Module
      version: v1.0
  apiDocs:
    enabled: true
  #        path: /v3/api  -docs?
  swaggerUi:
    enabled: true
#        path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
            defaultZone: https://bookamovie-spring-boot-eureka-server-fe3s.onrender.com/eureka
