server:
    port: 8082

spring:
    application:
        name: movie-and-theatre-module
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/Movie_DB?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        #        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update # Automatically updates the database schema based on entities
        show-sql: true # Logs SQL queries to the console
    session:
        jdbc:
            initialize-schema: always
    messages: # Use My Properties file: error.property
        basename: error
        encoding: UTF-8
        fallback-to-system-locale: false

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

springdoc:
    openapi:
        info:
            title: Movie REST API Documentation
            description: This is the REST API Documentation for the Movie and Theatre Module
            version: v1.0
    apiDocs:
        enabled: true
#        path: /v3/api  -docs?
    swaggerUi:
        enabled: true
#        path: /swagger-ui.html
